from __future__ import annotations
import logging
from pathlib import Path
import yaml

from phosp.config import SimulationConfig

logger = logging.getLogger(__name__)
_PRESETS_DIR = Path(__file__).parent


class Protocol:
    def __init__(self, data: dict, sim_config: SimulationConfig) -> None:
        self._data = data
        self._sim = sim_config

    @classmethod
    def load(cls, name_or_path: str, sim_config: SimulationConfig) -> Protocol:
        p = Path(name_or_path)
        if not p.suffix:
            p = _PRESETS_DIR / f"{name_or_path}.yaml"
        if not p.exists():
            raise FileNotFoundError(f"Protocol preset not found: {p}")
        data = yaml.safe_load(p.read_text())
        return cls(data, sim_config)

    def render_mdp(self, phase: str, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        params = dict(self._data.get(phase, {}))

        if phase == "production":
            dt = params.get("dt", 0.002)
            steps = int(self._sim.production_time_ns * 1000 / dt)
            params["nsteps"] = steps
            nstxout = max(1, int(self._sim.output_freq_ps / dt))
            params["nstxout_compressed"] = nstxout

        mdp_path = output_dir / f"{phase}.mdp"
        mdp_path.write_text(self._render(phase, params))
        logger.info("Wrote %s MDP → %s", phase, mdp_path)
        return mdp_path

    def _render(self, phase: str, params: dict) -> str:
        rvdw = self._data.get("rvdw_nm", 1.2)
        rcoulomb = self._data.get("rcoulomb_nm", rvdw)
        common = (
            "; Generated by phosp\n"
            "constraints          = h-bonds\n"
            "constraint-algorithm = lincs\n"
            "coulombtype          = PME\n"
            f"rcoulomb             = {rcoulomb}\n"
            f"rvdw                 = {rvdw}\n"
            "vdwtype              = Cut-off\n"
            "DispCorr             = EnerPres\n"
            "pbc                  = xyz\n\n"
        )
        if phase == "minimization":
            return common + (
                f"integrator = {params.get('integrator', 'steep')}\n"
                f"nsteps     = {params.get('nsteps', 50000)}\n"
                f"emtol      = {params.get('emtol', 1000.0)}\n"
                f"emstep     = {params.get('emstep', 0.01)}\n"
            )
        lines = [common]
        lines.append(f"integrator  = md\n")
        for key, val in params.items():
            mdp_key = key.replace("_", "-")
            lines.append(f"{mdp_key:<20} = {val}\n")
        return "".join(lines)
